# <center>TP 2</center>


- Exploration de l'environnement FrozenLake

In [1]:
import gymnasium as gym
import numpy as np

env = gym.make('FrozenLake-v1',is_slippery=True)

# Affichage des informations de l'espace d'état et d'action
print(f"Espace d'état: {env.observation_space}")  # Nombre d'états
print(f"Espace d'action: {env.action_space}")    # Nombre d'actions possibles


Espace d'état: Discrete(16)
Espace d'action: Discrete(4)


- Imlpementation de la Q-Table et Initialisation

In [2]:
# Récupérer le nombre d'états et d'actions
nb_etats = env.observation_space.n
nb_actions = env.action_space.n

# Création de la Q-table initialisée à zéro
Q_table = np.zeros((nb_etats, nb_actions))

# Affichage de la Q-table avant apprentissage
print("Q-table avant l'apprentissage :")
print(Q_table)

# Vérification que chaque état a une liste de valeurs associées aux actions possibles
for etat in range(nb_etats):
    print(f"État {etat}: {Q_table[etat]}")

Q-table avant l'apprentissage :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
État 0: [0. 0. 0. 0.]
État 1: [0. 0. 0. 0.]
État 2: [0. 0. 0. 0.]
État 3: [0. 0. 0. 0.]
État 4: [0. 0. 0. 0.]
État 5: [0. 0. 0. 0.]
État 6: [0. 0. 0. 0.]
État 7: [0. 0. 0. 0.]
État 8: [0. 0. 0. 0.]
État 9: [0. 0. 0. 0.]
État 10: [0. 0. 0. 0.]
État 11: [0. 0. 0. 0.]
État 12: [0. 0. 0. 0.]
État 13: [0. 0. 0. 0.]
État 14: [0. 0. 0. 0.]
État 15: [0. 0. 0. 0.]


- Implementation du Q-Learning avec Mise a jour

In [3]:
#Parametres
alpha= 0.1
gamma=0.99
epsilon=1.0
epsilon_decay=0.995
num_episodes=5000

#Boucle d'apprentissage
for _ in range(num_episodes):
     state, _ = env.reset()
     done = False
     while not done:
          if np.random.rand() < epsilon:
            action = env.action_space.sample()     #Exploration
          else:
            action = np.argmax(Q_table[state, :])  #Exploitation
          
          # Exécuter l'action et obtenir la récompense et le nouvel état  
          next_state, reward, done, _, _ = env.step(action)

          Q_table[state, action] += alpha * (reward + gamma * np.max(Q_table[next_state, :]) - Q_table[state, action])
          
          state = next_state
     
     epsilon *= epsilon_decay
     
env.close()
print(Q_table)


[[5.00511548e-01 4.14119636e-01 3.76693284e-01 3.78210308e-01]
 [1.77531987e-03 2.46640496e-01 2.44252704e-05 4.70902233e-02]
 [2.97856491e-01 3.82499183e-03 2.98266617e-02 2.17263079e-03]
 [4.93375594e-05 2.01334495e-05 0.00000000e+00 0.00000000e+00]
 [5.19151020e-01 3.78449133e-01 3.09760910e-01 3.02645706e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.52072562e-02 4.58775896e-02 2.36401788e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.12541366e-01 3.47521604e-01 3.42891612e-01 5.48434568e-01]
 [3.30037817e-01 5.82593893e-01 4.00582797e-01 1.97671396e-01]
 [5.72796838e-01 8.32165307e-02 2.68754571e-01 5.05302320e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.17494349e-01 3.07277205e-01 6.98458190e-01 2.61115799e-01]
 [3.82545567e-01 8.93329212e-01 4.61369789e-01 4.71516230e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000

- Evaluation des Performances de l'agent

In [ ]:
# Évaluation de l'agent après entraînement
num_test_episodes = 100
successes = 0  # Nombre de fois où l'agent atteint l'objectif


for episode in range(num_test_episodes):
    state = env.reset()[0]  # Réinitialiser l'environnement
    done = False

    while not done:
        # Sélectionner l'action optimale (greedy policy)
        action = np.argmax(Q_table[state])

        # Exécuter l'action
        next_state, reward, done, _, _ = env.step(action)

        # Si on atteint l'objectif (reward == 1), on compte une réussite
        if reward == 1:
            successes += 1

        # Passer à l'état suivant
        state = next_state
        

print(Q_table)

# Calcul du taux de réussite
taux_reussite = (successes / num_test_episodes) * 100
print(f"Taux de réussite de l'agent sur {num_test_episodes} épisodes : {taux_reussite:.2f}%")


[[5.00511548e-01 4.14119636e-01 3.76693284e-01 3.78210308e-01]
 [1.77531987e-03 2.46640496e-01 2.44252704e-05 4.70902233e-02]
 [2.97856491e-01 3.82499183e-03 2.98266617e-02 2.17263079e-03]
 [4.93375594e-05 2.01334495e-05 0.00000000e+00 0.00000000e+00]
 [5.19151020e-01 3.78449133e-01 3.09760910e-01 3.02645706e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.52072562e-02 4.58775896e-02 2.36401788e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.12541366e-01 3.47521604e-01 3.42891612e-01 5.48434568e-01]
 [3.30037817e-01 5.82593893e-01 4.00582797e-01 1.97671396e-01]
 [5.72796838e-01 8.32165307e-02 2.68754571e-01 5.05302320e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.17494349e-01 3.07277205e-01 6.98458190e-01 2.61115799e-01]
 [3.82545567e-01 8.93329212e-01 4.61369789e-01 4.71516230e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000